# Generated by Django 3.2.4 on 2021-07-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madera',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreMadera', models.CharField(max_length=15, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreMoneda', models.CharField(max_length=10, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('numIdentificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='Num identificacion')),
                ('nomCompleto', models.CharField(max_length=30, verbose_name='Nombre completo')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=20, verbose_name='Dirección')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('pais', models.CharField(max_length=15, verbose_name='País')),
                ('madera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.madera')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.moneda')),
            ],
        ),
    ]
